repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace
    -   id: check-xml
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: ["--indent=4", "--autofix", "--no-sort-keys"]
#-   repo: https://github.com/eriocnemis/git.MagentoPreCommitHooks
#    rev: 1.0.7
#    hooks:
#    -   id: magento-phpcs
#    -   id: magento-phpmd
#    -   id: magento-phpcpd
#    -   id: magento-phpstan
